#
# This file is part of Cisco Modeling Labs
# Copyright (c) 2019-2024, Cisco Systems, Inc.
# All rights reserved.
#

steps:
  - name: 'us-east1-docker.pkg.dev/gcp-asigbahgcp-nprd-47930/bah-builders/cloud-cml-img'
    env:
      # If set to true, the build will pause on failures and allow project-level 
      # SSH keys to Packer machines.  Depending on the stage of install failuare,
      # SSH might be listening on port 1122.
      - 'DEBUG=true'
      - 'PACKER_LOG=0'
      # Discover these with `gcloud compute images list --project ubuntu-os-cloud`
      - 'SOURCE_IMAGE_FAMILY=ubuntu-2404-lts-amd64'
      - 'SOURCE_IMAGE_PROJECT_ID=ubuntu-os-cloud'
      - 'PROVISION_SCRIPT=cml.sh'
      - 'GCS_ARTIFACT_BUCKET=bah-machine-images'
      - 'CML_PACKAGE_PATH=cml2/cml2_2.8.1-14_amd64-35.pkg'
      - 'CML_VERSION=2-8-1'
      - 'LOCATION=$LOCATION'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'LOCATION=${LOCATION}'
      - 'ZONE=${LOCATION}-b'
      - 'SERVICE_ACCOUNT_EMAIL=$SERVICE_ACCOUNT_EMAIL'
      # Also see refplat.json for the list of node definitions and images to
      # include on the controller

    script: |
      #!/usr/bin/env bash

      set -e
      #set -x

      echo "Locale settings:"
      cat /etc/default/locale

      cd /workspace
      git describe --all --long --tags --dirty 2>/dev/null | cut -d '/' -f 2 > /workspace/build-git-ref.txt

      # Build Cisco Modeling Labs image with Packer
      packer init /workspace/cloud-cml-gce.pkr.hcl
      packer validate \
        -var "debug=$DEBUG" \
        -var "service_account_email=$SERVICE_ACCOUNT_EMAIL" \
        -var "location=$LOCATION" \
        -var "zone=$ZONE" \
        -var "project_id=$PROJECT_ID" \
        -var "source_image_family=$SOURCE_IMAGE_FAMILY" \
        -var "source_image_project_id=$SOURCE_IMAGE_PROJECT_ID" \
        -var "provision_script=$PROVISION_SCRIPT" \
        -var "gcs_artifact_bucket=$GCS_ARTIFACT_BUCKET" \
        -var "cml_package_path=$CML_PACKAGE_PATH" \
        -var "cml_version=$CML_VERSION" \
        /workspace/cloud-cml-gce.pkr.hcl
      packer build \
        -var "debug=$DEBUG" \
        -var "service_account_email=$SERVICE_ACCOUNT_EMAIL" \
        -var "location=$LOCATION" \
        -var "zone=$ZONE" \
        -var "project_id=$PROJECT_ID" \
        -var "source_image_family=$SOURCE_IMAGE_FAMILY" \
        -var "source_image_project_id=$SOURCE_IMAGE_PROJECT_ID" \
        -var "provision_script=$PROVISION_SCRIPT" \
        -var "gcs_artifact_bucket=$GCS_ARTIFACT_BUCKET" \
        -var "cml_package_path=$CML_PACKAGE_PATH" \
        -var "cml_version=$CML_VERSION" \
        /workspace/cloud-cml-gce.pkr.hcl

      # If packer creates artifacts, list them
      [ -f /workspace/manifest.json ] && jq . /workspace/manifest.json


logsBucket: 'gs://bah-build-logs/cloud-cml-img'
serviceAccount: 'projects/gcp-asigbahgcp-nprd-47930/serviceAccounts/build-cloud-cml-img@gcp-asigbahgcp-nprd-47930.iam.gserviceaccount.com'

options:
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
