#
# This file is part of Cisco Modeling Labs
# Copyright (c) 2019-2023, Cisco Systems, Inc.
# All rights reserved.
#

#
# This is the configuration file for the CML bootstrap script.
#

# Keep the build machine running if the build fails
debug: true

# Image version
version: 0.1.0

# AWS configs
aws:
  region: us-east-2
  vpc: cmm-vpc
  availability_zone: us-east-2a
  subnet: cmm-subnet-public1-us-east-2a
  security_group: default

  # The S3 bucket where reference platforms are stored
  bucket: bah-machine-images

  # TODO cmm - CiscoModelingLabs role must not be able to access this bucket
  # Must be globally unique and updated in terraform.tf backend config
  tfstate_bucket: cml-tfstate-bucket
  tfstate_key: cloud-cml-img/terraform.tfstate

  # The EC2 instance type to use.  Use a .metal type for /dev/kvm support.
  #flavor: z1d.metal
  #flavor: c5n.metal
  flavor: c5d.xlarge

  # IAM Role for EC2 host to assume
  profile: CiscoModelingLabsBuild

  ssh_key_name: bootstrap_ssh
  disk_size: 16

cml:
  debian_package: cml2_2.7.0dev0-1660_amd64.deb

  copy_reference_platforms: true
  # select the ones needed by un-/commenting them. The selected
  # reference platforms will be copied from the specified bucket
  # and must be available prior to starting an instance.
  reference_platforms:
    definitions:
      - alpine
      - alpine-trex
      - alpine-wanem
      - asav
      - cat8000v
      - cat9000v-q200
      - cat9000v-uadp
      - csr1000v
      - desktop
      - iol-xe
      - ioll2-xe
      - iosv
      - iosvl2
      - iosxrv9000
      - nxosv9000
      - server
      - ubuntu
    images:
      - alpine-base-3-19-1
      - alpine-desktop-3-19-1
      - alpine-trex-3-19-1
      - alpine-wanem-3-19-1
      - asav-9-20-2
      - cat8000v-17-13-01a
      - cat9000v-q200-17-12-01prd9
      - cat9000v-uadp-17-12-01prd9
      - csr1000v-17-03-08a
      - iol-xe-17-12-01
      - ioll2-xe-17-12-01
      - iosv-159-3-m8
      - iosvl2-2020
      - iosxrv9000-7-11-1
      - nxosv9300-10-4-2-f
      - server-tcl-14-0
      - ubuntu-22-04-20240126
