#
# This file is part of Cisco Modeling Labs
# Copyright (c) 2019-2024, Cisco Systems, Inc.
# All rights reserved.
#
admins:
  controller:
    password: ""
    username: ""
  system:
    password: ""
    username: ""
cluster_interface: ""
compute_secret: ""
controller_name: ""
copy_iso_to_disk: false
hostname: ""
interactive: false
is_cluster: ""
is_compute: true
is_configured: false
is_controller: false
primary_interface: ""
ssh_server: true
use_ipv4_dhcp: true
skip_primary_bridge: true
